SSO_firstApp/Models/ErrorViewModel.cs
using System;

namespace LiveMusicFinder.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SSO_firstApp/Models/LiveShow.cs
using System;

namespace LiveMusicFinder.Models
{
    public class LiveShow
    {
        public int Id { get; set; }
        public string Artist { get; set; }
        public string Venue { get; set; }
        public DateTime ShowDate { get; set; }
        public string EnteredBy { get; set; }
    }
}

SSO_firstApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Okta.AspNetCore;

namespace LiveMusicFinder.Controllers
{
  public class AccountController : Controller
  {
    public IActionResult Login()
    {
      if (!HttpContext.User.Identity.IsAuthenticated)
      {
        return Challenge(OktaDefaults.MvcAuthenticationScheme);
      }
      return RedirectToAction("Index", "Home");
    }

    public IActionResult Logout()
    {
      return new SignOutResult(new[]
      {
            OktaDefaults.MvcAuthenticationScheme,
            CookieAuthenticationDefaults.AuthenticationScheme
          });
    }

    public IActionResult PostLogout()
    {
      return RedirectToAction("Index", "Home");
    }
  }
}

SSO_firstApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LiveMusicFinder.Models;

namespace LiveMusicFinder.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SSO_firstApp/Controllers/LiveShowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LiveMusicFinder.Data;
using LiveMusicFinder.Models;
using Microsoft.AspNetCore.Authorization;

namespace Controllers
{
  public class LiveShowsController : Controller
  {
    private readonly ApplicationDbContext _context;

    public LiveShowsController(ApplicationDbContext context)
    {
      _context = context;
    }

    // GET: LiveShows
    public async Task<IActionResult> Index()
    {
      return View(await _context.LiveShows.ToListAsync());
    }

    // GET: LiveShows/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var liveShow = await _context.LiveShows
          .FirstOrDefaultAsync(m => m.Id == id);
      if (liveShow == null)
      {
        return NotFound();
      }

      return View(liveShow);
    }

    // GET: LiveShows/Create
    [Authorize]
    public IActionResult Create()
    {
      return View();
    }

    // POST: LiveShows/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize]
    public async Task<IActionResult> Create([Bind("Id,Artist,Venue,ShowDate")] LiveShow liveShow)
    {
      liveShow.EnteredBy = User.Identity.Name;
      if (ModelState.IsValid)
      {
        _context.Add(liveShow);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      return View(liveShow);
    }

    // GET: LiveShows/Edit/5
    [Authorize]
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var liveShow = await _context.LiveShows.FindAsync(id);
      if (liveShow == null)
      {
        return NotFound();
      }
      return View(liveShow);
    }

    // POST: LiveShows/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Artist,Venue,ShowDate")] LiveShow liveShow)
    {
      liveShow.EnteredBy = User.Identity.Name;
      if (id != liveShow.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(liveShow);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!LiveShowExists(liveShow.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }
        return RedirectToAction(nameof(Index));
      }
      return View(liveShow);
    }

    // GET: LiveShows/Delete/5
    [Authorize]
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var liveShow = await _context.LiveShows
          .FirstOrDefaultAsync(m => m.Id == id);
      if (liveShow == null)
      {
        return NotFound();
      }

      return View(liveShow);
    }

    // POST: LiveShows/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Authorize]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var liveShow = await _context.LiveShows.FindAsync(id);
      _context.LiveShows.Remove(liveShow);
      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool LiveShowExists(int id)
    {
      return _context.LiveShows.Any(e => e.Id == id);
    }
  }
}

SSO_firstApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SSO_firstApp/Views/LiveShows/Create.cshtml
@model LiveMusicFinder.Models.LiveShow

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>LiveShow</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <input asp-for="Venue" class="form-control" />
                <span asp-validation-for="Venue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShowDate" class="control-label"></label>
                <input asp-for="ShowDate" class="form-control" />
                <span asp-validation-for="ShowDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SSO_firstApp/Views/LiveShows/Delete.cshtml
@model LiveMusicFinder.Models.LiveShow

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LiveShow</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Venue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShowDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShowDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnteredBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnteredBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SSO_firstApp/Views/LiveShows/Details.cshtml
@model LiveMusicFinder.Models.LiveShow

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>LiveShow</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Venue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShowDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShowDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnteredBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnteredBy)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && Model.EnteredBy == User.Identity.Name)
    {
      <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a><span> |</span>
      <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a><span> |</span>
    }
    <a asp-action="Index">Back to List</a>
</div>

SSO_firstApp/Views/LiveShows/Edit.cshtml
@model LiveMusicFinder.Models.LiveShow

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>LiveShow</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <input asp-for="Venue" class="form-control" />
                <span asp-validation-for="Venue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShowDate" class="control-label"></label>
                <input asp-for="ShowDate" class="form-control" />
                <span asp-validation-for="ShowDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SSO_firstApp/Views/LiveShows/Index.cshtml
@model IEnumerable<LiveMusicFinder.Models.LiveShow>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
      <tr>
        <th>
            @Html.DisplayNameFor(model => model.Artist)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Venue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShowDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnteredBy)
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model) {  
      <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Artist)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Venue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShowDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EnteredBy)
        </td>
        
        <td>
          <a asp-action="Details" asp-route-id="@item.Id">Details</a>
          @if (User.Identity.IsAuthenticated && item.EnteredBy == User.Identity.Name)
          {
            <span> |</span>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a><span> |</span>
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
          }
        </td>
      </tr>
      }
    </tbody>
</table>

SSO_firstApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LiveMusicFinder</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LiveMusicFinder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-between">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LiveShows" asp-action="Index">Live Shows</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - LiveMusicFinder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>